exports.CART_TYPE = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART'
}
exports.LOAD_DATA = {
    LOAD_STARTING: 'LOAD_STARTING',
    LOAD_FINISH: 'LOAD_FINISH'
}
exports.FILTER_TYPE = {
    TOGGLE_BRAND: 'TOGGLE_BRAND',
    TOGGLE_STOCK: 'TOGGLE_STOCK'
}